# 语法 https://docs.github.com/zh/actions/reference/workflow-syntax-for-github-actions
name: Build App (macos-arm64)
on: workflow_dispatch # 手动触发

jobs:
  build: # <job_id>
    runs-on: macos-15
    steps: # 每个step运行在单独的进程中
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10
      
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
          
      - name: Install Python dependencies (distutils)
        run: |
          python3 -m ensurepip --default-pip
          python3 -m pip install --upgrade pip 
          python3 -m pip install setuptools wheel

      - name: Install dependencies
        run: pnpm install
      
      - name: Make
        run: pnpm run make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TrPlayer-${{ runner.os }}-arm64-build-${{ github.ref_name}}
          path: |
            out/make/**/*.dmg
   

